version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: identity-forecaster-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./identity-forecaster-postgres:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 7s
      timeout: 7s
      retries: 5
    command: [ "postgres", "-c", "log_statement=all" ]
  identity-forecaster:
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      IN_CONTAINER: true
    ports:
      - "${PORT}:${PORT}"